# Generated by Django 2.1.1 on 2019-06-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemCategory',
            new_name='AttributeCategory',
        ),
    ]
