# Generated by Django 2.2.2 on 2019-06-17 17:04

from django.db import migrations, models
import recommender.models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20190616_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gps_point',
            field=models.CharField(blank=True, max_length=140, verbose_name='GPS Point'),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recommender.models.item_upload_to, verbose_name='Item image'),
        ),
        migrations.AddField(
            model_name='item',
            name='weblink',
            field=models.URLField(blank=True, max_length=140, verbose_name='Web link'),
        ),
    ]
