# Generated by Django 2.1.1 on 2018-09-27 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_customuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=140, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Valoration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=140, verbose_name='Comment')),
                ('score', models.CharField(blank=True, max_length=140, verbose_name='Score')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valorated_item', to='recommender.Item', verbose_name='Valorated item')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='recommender.ItemType', verbose_name='Preferences'),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AddField(
            model_name='group',
            name='valorations',
            field=models.ManyToManyField(blank=True, to='recommender.Valoration', verbose_name='Valorations'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='recommender.ItemType', verbose_name='Preferences'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='valorations',
            field=models.ManyToManyField(blank=True, to='recommender.Valoration', verbose_name='Valorations'),
        ),
        migrations.AddField(
            model_name='item',
            name='types',
            field=models.ManyToManyField(blank=True, to='recommender.ItemType', verbose_name='Types'),
        ),
    ]
