# Generated by Django 2.1.1 on 2018-09-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20180927_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='valoration',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='valoration',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
    ]
