# Generated by Django 2.2.2 on 2019-06-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_auto_20190617_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedent',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='consequent',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='pertenancegrade',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Weight'),
        ),
    ]
