# Generated by Django 2.1.1 on 2018-10-11 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_auto_20180927_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='accepted_terms',
        ),
    ]
