# Generated by Django 2.2.2 on 2019-06-24 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contextsegment',
            name='implications',
        ),
        migrations.AddField(
            model_name='implication',
            name='context_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implications', to='recommender.ContextSegment', verbose_name='Context segment'),
            preserve_default=False,
        ),
    ]
