# Generated by Django 2.2.2 on 2019-09-17 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_auto_20190917_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='context_segments',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='context_segment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommender.ContextSegment', verbose_name='Context segment'),
            preserve_default=False,
        ),
    ]
