# Generated by Django 2.2.2 on 2019-09-17 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0010_auto_20190917_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationcontext',
            name='context_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_contexts', to='recommender.ContextSegment', verbose_name='Context segment'),
        ),
    ]
