# Generated by Django 2.2.2 on 2019-09-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0011_auto_20190917_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencegrade',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Value'),
        ),
    ]
