# Generated by Django 2.2.2 on 2019-09-18 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0012_auto_20190918_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date',
        ),
    ]
